VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsEventsForWidgets"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
''
' Calendar v1.0
' 
' (c) CDevZero - https://github.com/CDevZero/Calendar-VBA
'
' @class clsEventsForWidgets
' @author nathandrakehs@gmail.com
' @license MIT http://www.opensource.org/licenses/mit-license.php
'' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ '

Option Explicit

' ============================================= '
' Public Methods
' ============================================= '

''
' @method DblClick
' @param {Date} ReturnDate
''

Public Sub DblClick(ByVal ReturnDate As Date)
End Sub

''
' @method MouseMove
' @param {Integer} WidgetIndex
' @param {Single} X
' @param {Single} Y
''

Public Sub MouseMove(ByVal WidgetIndex As Integer, ByVal X As Single, ByVal Y As Single)
End Sub